### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by Yoreni** [lolteam4u/SRP#1]
ur repo suk evething broke

**Comment by lolteam4u** [comment]
Hi there hope you well I was just wondering what issue you were having and also why you haven’t given a detailed error you are receiving and just looking at your GitHub account well I have a few questions first of the ascii Tetris looks like something a 10 year old scratch dev would make and try and sell it litterly the memes fork for a bucket server you litterly stole https://github.com/Yoreni/MountainDewritoes from someone’s and forked it and done what ever you did to it like whoah at least credit the original author in your code you litterly cannot spell for life you put 			else player.sendMessage(ChatColor.RED + "m8 u dont have perms");
It should be You Don’t Have Permission line 388 
scrub
https://github.com/Yoreni/MLGprison/blob/master/src/yoreni/MLGprison/main/Main.java
Many Thanks
Get Better Coding Skills or just Alt F4 your GitHub
Lolteam4U

**Comment by Yoreni** [comment]
OOF
